### PR TITLE
Make lab extension list more verbose about errors

### LINKED ISSUE #1203: Make `jupyter labextension` more verbose
I think the following information would be really helpful to display in `jupyter labextension`:

1. The path to the module
2. If there is a warning (like the semver check failing from #1190), giving a list of the modules that failed it.
3. the necessary files check should display which files are missing
4. has entry could specify which of the conditions it is checking that is false.

Basically, it would be very helpful to be explicit about exactly what files we are checking, and what is wrong with them.

### PR DESCRIPTION
**Pull request by jasongrout**
Fixes #1203

### CODE REVIEW

**Comment by blink1073** [comment]
The Travis failure is legitimate: 


```
======================================================================
ERROR: Failure: ImportError (cannot import name 'validate_labextension')
----------------------------------------------------------------------
```

**Comment by jasongrout** [comment]
> The Travis failure is legitimate:

Thanks, I'll add tests Monday.

**Comment by jasongrout** [comment]
@blink1073 - I added tests...

**Comment by blink1073** [comment]
Thanks!
