### ISSUE TITLE
How to add/insert a new cell with pre defined content to cellList in 4.0.2

### ISSUE THREAD

**Issue by ShilpaShivaji** [jupyterlab/jupyterlab#14730]
We are using notebook extension example in our application and inserting a pre defined code to a cell at specified index.

     const code = "some code";
     const index = this.currentNotebookEditor.notebookPanel.content.activeCellIndex + 1;
        this.currentNotebookEditor.notebookPanel.content.model.cells.insert(
            index,
            new CodeCellModel({
                cell: {
                    source: code,
                    cell_type: 'code',
                    metadata: {},
                },
            })
        );
        
 This works fine in older versions of jupyterlab. After upgrading to 4.0.2,    this.currentNotebookEditor.notebookPanel.content.model.cells.insert() is giving error "Property 'insert' does not exist on type 'CellList'. 
I see that "cells" is of type cells: CellList; - 4.0.2 version
In older version "cells" was of type  cells: IObservableUndoableList<ICellModel>; - older versions

How to add a new cell to the cellList in 4.0.2 ?

**Comment by fcollonval** [comment]
Hey @ShilpaShivaji you will now have to use the shared model and insert directly a JSON blob. See for example the implementation for splitting a cell:

https://github.com/jupyterlab/jupyterlab/blob/39597083b554ae66563dec5cdf1af893c1a02cfc/packages/notebook/src/actions.tsx#L210-L210

**Comment by ShilpaShivaji** [comment]
@fcollonval Thanks. This is working.

**Comment by adijo** [comment]
@fcollonval thanks. Would it be possible to use the functions in `NotebookActions` directly? I tried the following but the `activeCellIndex` never gets updated. Would appreciate any help, thanks!

```
const plugin: JupyterFrontEndPlugin<void> = {
  id: 'test:plugin',
  description: 'A JupyterLab extension.',
  autoStart: true,
  requires: [INotebookTracker],
  activate: (app: JupyterFrontEnd, nbtracker: INotebookTracker) => {
    console.log('JupyterLab extension dynaterm is activated!');

    nbtracker.currentChanged.connect(() => {
      console.log("Notebook Panel's current widget changed. Signal emitted.");
      if (nbtracker.currentWidget) {
        console.log('Notebook Panel is active: ', nbtracker.currentWidget);

        const notebookPanel = nbtracker.currentWidget;
        const notebook = notebookPanel.content;
        notebook.mode = 'edit';

        console.log(notebook.activeCellIndex);

        NotebookActions.insertAbove(notebook);

        console.log(notebook.activeCellIndex);
      }
    });
  }
};
```
