### PR TITLE
Dev deps: Resolve to as-of-yet-unreleased node-canvas version

### PR DESCRIPTION
**Pull request by akx**
## References

No referenced issue, but the gist of it is that you can't do `pip install -e .` on certain unlucky combinations of Python version, Node version and CPU architecture, because:

* node-canvas has no pre-built packages for recent Node ABIs and/or CPU architectures:
  ```
  node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@21.1.0 (node-v120 ABI, unknown) (falling back to source compile with node-gyp)
  ```
* `gyp` fails to work on Python 3.12 if `setuptools` isn't separately installed in the ambient environment (related: https://github.com/nodejs/gyp-next/pull/214/files)
* even if `gyp` worked on Python 3.12, building node-canvas against node-v120 ABI fails because of API changes that `nan` isn't aware of:
  ```
  /Users/akx/Library/Caches/node-gyp/21.1.0/include/node/v8-local-handle.h:253:5: error: static assertion failed due to requirement 'std::is_base_of<v8::Value, v8::Data>::value': type check
      static_assert(std::is_base_of<T, S>::value, "type check");
      ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ../../nan/nan_callbacks_12_inl.h:175:20: note: in instantiation of function template specialization 'v8::Local<v8::Value>::Local<v8::Data>' requested here
        cbinfo(info, obj->GetInternalField(kDataIndex));
  ```

This leads to `pip install -e .` failing because `canvas` is a development dependency:

```
$ pip install -e ".[dev,test]"
Obtaining file:///Users/akx/build/jupyterlab
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [157 lines of output]
      INFO:hatch_jupyter_builder.utils:Running jupyter-builder
      WARNING:hatch_jupyter_builder.utils:Refusing to overwrite pre-commit hook
      INFO:hatch_jupyter_builder.utils:Building with buildapi.builder
      INFO:hatch_jupyter_builder.utils:With kwargs: {'build_cmd': 'build', 'source_dir': 'packages', 'build_dir': 'dev_mode/static', 'npm': ['node', 'jupyterlab/staging/yarn.js']}
      INFO:hatch_jupyter_builder.utils:Installing build dependencies with npm.  This may take a while...
      INFO:hatch_jupyter_builder.utils:> /opt/homebrew/bin/node jupyterlab/staging/yarn.js install
      [...snip...]
      ➤ YN0000: ┌ Link step
      ➤ YN0009: │ canvas@npm:2.11.2 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/nz/6mg9yzdj1kq8lg2tsc5y9rlc0000gn/T/xfs-e51483d2/build.log)
      ➤ YN0000: └ Completed in 1s 423ms
      ➤ YN0000: Failed with errors in 1s 986ms
$
```

Using the newer (unreleased) version fixes this since they've switched to the new more version-agnostic n-api API: https://github.com/Automattic/node-canvas/pull/2235

I don't know if/when the node-canvas folks are going to release node-canvas 3.0, but this should work in the meantime...

## Code changes

No code changes, just a dependency resolution change.

## User-facing changes

None.

## Backwards-incompatible changes

None.

### CODE REVIEW

**Comment by akx** [comment]
Well, looking at CI, the flipside of this is that there are no prebuilds of the unreleased version at all, so everything's broken in another way.

Closing this for now, but maybe this'll help someone googling for the symptoms above :)
