### ISSUE TITLE
AttributeError: 'Version' object has no attribute 'major'

### ISSUE THREAD

**Issue by thoward27** [jupyterlab/jupyterlab#10111]
## Description

Using `python3.9.4`, installing `jupter lab` fails. Seems to be an issue with the packaging library.

## Reproduce

1. Install python 3.9.4 using pyenv `pyenv install 3.9.4`
2. Create a virtual environment `python -m venv .venv`
3. Activate it `source .venv/bin/activate`
4. Try to start jupyter lab.
5. See this error:

```
Traceback (most recent call last):
  File "/Users/thomas/.pyenv/versions/3.9.4/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/thomas/.pyenv/versions/3.9.4/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/thomas/.pyenv/versions/3.9.4/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/thomas/Scratch/foo/.venv/lib/python3.9/site-packages/jupyterlab/__init__.py", line 7, in <module>
    from .labapp import LabApp
  File "/Users/thomas/Scratch/foo/.venv/lib/python3.9/site-packages/jupyterlab/labapp.py", line 15, in <module>
    from jupyterlab_server import slugify, WORKSPACE_EXTENSION
  File "/Users/thomas/Scratch/foo/.venv/lib/python3.9/site-packages/jupyterlab_server/__init__.py", line 4, in <module>
    from .app import LabServerApp
  File "/Users/thomas/Scratch/foo/.venv/lib/python3.9/site-packages/jupyterlab_server/app.py", line 7, in <module>
    from jupyter_server.extension.application import ExtensionApp, ExtensionAppJinjaMixin
  File "/Users/thomas/Scratch/foo/.venv/lib/python3.9/site-packages/jupyter_server/__init__.py", line 15, in <module>
    from ._version import version_info, __version__
  File "/Users/thomas/Scratch/foo/.venv/lib/python3.9/site-packages/jupyter_server/_version.py", line 9, in <module>
    version_info = get_version_info(__version__)
  File "/Users/thomas/Scratch/foo/.venv/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 249, in get_version_info
    version_info = [parsed.major, parsed.minor, parsed.micro]
AttributeError: 'Version' object has no attribute 'major'
```

## Expected behavior

Installation should work.

## Context

- Operating System and version: MacOS Catalina (10.15.7)
- Browser and version: Chrome (not getting to the browser though)
- JupyterLab version: 3.0.14

<details><summary>Troubleshoot Output</summary>
<pre>
16:17 ❯ jupyter troubleshoot
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the '/Users/thomas/Scratch/foo/.venv/bin/python -m pip install --upgrade pip' command.
$PATH:
	/usr/local/Cellar/pyenv/1.2.26/libexec
	/usr/local/Cellar/pyenv/1.2.26/plugins/python-build/bin
	/Users/thomas/Scratch/foo/.venv/bin
	/Users/thomas/.local/bin
	/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims
	/Users/thomas/.pyenv/shims
	/Users/thomas/.pyenv/bin
	/opt/local/bin
	/opt/local/sbin
	/Users/thomas/bin
	/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims
	/Users/thomas/.pyenv/shims
	/Users/thomas/.nvm/versions/node/v10.15.3/bin
	/Users/thomas/go/bin
	/usr/local/bin
	/usr/local/opt/thrift@0.9/bin
	/Users/username/.pyenv
	/usr/local/opt/curl/bin
	/usr/local/opt/libiconv/bin
	/Users/thomas/Builds/flutter/bin
	/Users/thomas/.cargo/bin
	/usr/bin
	/bin
	/usr/sbin
	/sbin
	/Library/Apple/usr/bin
	/Users/thomas/.yarn/bin
	/Users/thomas/src/zcode/utils
	/Users/thomas/.local/bin
	/Users/thomas/.local/bin

sys.path:
	/Users/thomas/Scratch/foo/.venv/bin
	/Users/thomas/.pyenv/versions/3.9.4/lib/python39.zip
	/Users/thomas/.pyenv/versions/3.9.4/lib/python3.9
	/Users/thomas/.pyenv/versions/3.9.4/lib/python3.9/lib-dynload
	/Users/thomas/Scratch/foo/.venv/lib/python3.9/site-packages

sys.executable:
	/Users/thomas/Scratch/foo/.venv/bin/python

sys.version:
	3.9.4 (default, Apr 16 2021, 15:55:15) 
	[Clang 12.0.0 (clang-1200.0.32.29)]

platform.platform():
	macOS-10.15.7-x86_64-i386-64bit

which -a jupyter:
	/Users/thomas/Scratch/foo/.venv/bin/jupyter
	/Users/thomas/.pyenv/shims/jupyter
	/Users/thomas/.pyenv/shims/jupyter

pip list:
	Package             Version
	------------------- ---------
	anyio               2.2.0
	appnope             0.1.2
	argon2-cffi         20.1.0
	async-generator     1.10
	attrs               20.3.0
	Babel               2.9.0
	backcall            0.2.0
	bleach              3.3.0
	certifi             2020.12.5
	cffi                1.14.5
	chardet             4.0.0
	decorator           5.0.7
	defusedxml          0.7.1
	deprecation         2.1.0
	entrypoints         0.3
	idna                3.1
	ipykernel           5.5.3
	ipython             7.22.0
	ipython-genutils    0.2.0
	jedi                0.18.0
	Jinja2              2.11.3
	json5               0.9.5
	jsonschema          3.2.0
	jupyter-client      6.1.12
	jupyter-core        4.7.1
	jupyter-packaging   0.9.1
	jupyter-server      1.6.2
	jupyterlab          3.0.14
	jupyterlab-pygments 0.1.2
	jupyterlab-server   2.4.0
	MarkupSafe          1.1.1
	mistune             0.8.4
	nbclassic           0.2.7
	nbclient            0.5.3
	nbconvert           6.0.7
	nbformat            5.1.3
	nest-asyncio        1.5.1
	notebook            6.3.0
	packaging           20.0
	pandocfilters       1.4.3
	parso               0.8.2
	pexpect             4.8.0
	pickleshare         0.7.5
	pip                 20.2.3
	prometheus-client   0.10.1
	prompt-toolkit      3.0.18
	ptyprocess          0.7.0
	pycparser           2.20
	Pygments            2.8.1
	pyparsing           2.4.7
	pyrsistent          0.17.3
	python-dateutil     2.8.1
	pytz                2021.1
	pyzmq               22.0.3
	requests            2.25.1
	Send2Trash          1.5.0
	setuptools          49.2.1
	six                 1.15.0
	sniffio             1.2.0
	terminado           0.9.4
	testpath            0.4.4
	tomlkit             0.7.0
	tornado             6.1
	traitlets           5.0.5
	urllib3             1.26.4
	wcwidth             0.2.5
	webencodings        0.5.1
	wheel               0.36.2
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Traceback (most recent call last):
  File "/Users/thomas/Scratch/foo/.venv/bin/jupyter-lab", line 5, in <module>
    from jupyterlab.labapp import main
  File "/Users/thomas/Scratch/foo/.venv/lib/python3.9/site-packages/jupyterlab/__init__.py", line 7, in <module>
    from .labapp import LabApp
  File "/Users/thomas/Scratch/foo/.venv/lib/python3.9/site-packages/jupyterlab/labapp.py", line 15, in <module>
    from jupyterlab_server import slugify, WORKSPACE_EXTENSION
  File "/Users/thomas/Scratch/foo/.venv/lib/python3.9/site-packages/jupyterlab_server/__init__.py", line 4, in <module>
    from .app import LabServerApp
  File "/Users/thomas/Scratch/foo/.venv/lib/python3.9/site-packages/jupyterlab_server/app.py", line 7, in <module>
    from jupyter_server.extension.application import ExtensionApp, ExtensionAppJinjaMixin
  File "/Users/thomas/Scratch/foo/.venv/lib/python3.9/site-packages/jupyter_server/__init__.py", line 15, in <module>
    from ._version import version_info, __version__
  File "/Users/thomas/Scratch/foo/.venv/lib/python3.9/site-packages/jupyter_server/_version.py", line 9, in <module>
    version_info = get_version_info(__version__)
  File "/Users/thomas/Scratch/foo/.venv/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 249, in get_version_info
    version_info = [parsed.major, parsed.minor, parsed.micro]
AttributeError: 'Version' object has no attribute 'major</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by afshin** [comment]
Hi @thoward27, please try `pip install -U setuptools` from within your virtual env.  For some reason this requirement is not being satisfied:

https://github.com/jupyter/jupyter-packaging/blob/b4d94463ff83e8a3e487e7011c456652e0963370/setup.cfg#L32

**Comment by atrawog** [comment]
I just bumped into the same error on my Archlinux based Docker build using Pyenv and Python 3.8.8.

Things worked fine with jupyterlab-3.0.12 and I will see if I can narrow down the problem any further.

**Comment by half0wl** [comment]
> Hi @thoward27, please try `pip install -U setuptools` from within your virtual env. For some reason this requirement is not being satisfied:
> 
> https://github.com/jupyter/jupyter-packaging/blob/b4d94463ff83e8a3e487e7011c456652e0963370/setup.cfg#L32

I can verify that `pip install -U setuptools` fixes this in my Python 3.8.5 environment. Thanks @afshin!

**Comment by blink1073** [comment]
This should be fixed by  jupyter/jupyter-packaging#82, `pip install -U jupyter-packaging`
