### PR TITLE
Revert target to ES2017

### LINKED ISSUE #13913: New target in 3.6.0 induces downstream error
FYI, I think this caused our builds to fail with:

```
node_modules/@jupyterlab/services/lib/event/index.d.ts(89,52): error TS2583: Cannot find name 'AsyncIterable'. Do you need to change your target library? Try changing the `lib` compiler option to 'es2018' or later.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

_Originally posted by @maartenbreddels in https://github.com/jupyterlab/jupyterlab/issues/13052#issuecomment-1413919481_

The change was introduced by https://github.com/jupyterlab/jupyterlab/pull/13465

### PR DESCRIPTION
**Pull request by fcollonval**
## References

Fix #13913

## Code changes

Revert TypeScript target to "ES2017" and add a migration note.

## User-facing changes

None

## Backwards-incompatible changes

None - the emitted type will still include `AsyncIterable` and require downstream consumer to either add it to TypeScript lib or bump their target to ES2018.

### CODE REVIEW

File: docs/source/extension/extension_migration.rst [hunk 1]
```diff
@@ -1,13 +1,25 @@
...
 
 JupyterLab 3.5 to 3.6
 ---------------------
 
+AsyncIterable Support
+^^^^^^^^^^^^^^^^^^^^^
+
+For the events service, we are using a JavaScript feature introduced in ES2018. If your code is
+using TypeScript with ES2017 target (as JupyterLab 3.6), you will have either to update your
+target to ES2018 or to add ``"ES2018"`` to `TypeScript lib option <https://www.typescriptlang.org/tsconfig#lib>`_.
```
Comment (jasongrout) [inline docs/source/extension/extension_migration.rst:16]:
```suggestion
using TypeScript with ES2017 target (as JupyterLab 3.6), you will either need to update your
target to ES2018 or add ``"ES2018"`` to the `TypeScript lib option <https://www.typescriptlang.org/tsconfig#lib>`_.
```

File: docs/source/extension/extension_migration.rst [hunk 2]
```diff
@@ -1,13 +1,25 @@
...
+
+.. note::
+
+    JupyterLab 3.6.0 was released with an updated target "ES2018". We strongly advice updating to 3.6.1
+    that revert the target to "ES2017".
```
Comment (jasongrout) [inline docs/source/extension/extension_migration.rst:21]:
```suggestion
    JupyterLab 3.6.0 was released with an updated target "ES2018". We strongly advise updating to 3.6.1,
    which reverts the target back to "ES2017".
```
