### ISSUE TITLE
[3.1.0rc2] `jupyterlab-fasta` fails to render: `t.on is not a function`

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#10675]
## Description

The `jupyterlab-fasta` extension does not work with `3.1.0rc2`.

It might also be the case with other mimerender extensions.

## Reproduce

Can be reproduced with this gist:

- https://gist.github.com/jtpio/844ab4e85ae84f230cbcb0e56a59c88e
- https://mybinder.org/v2/gist/jtpio/844ab4e85ae84f230cbcb0e56a59c88e/master?urlpath=/lab

![image](https://user-images.githubusercontent.com/591645/126602114-340a8b2e-9256-42ac-99dd-5a2308f11fd3.png)

## Expected behavior

The `jupyterlab-fasta` extensions should work out of the box with JupyterLab 3.1.

## Context

Originally reported by @bollwyvl in https://github.com/jupyterlite/jupyterlite/issues/284

- Operating System and version: Ubuntu 20.04
- Browser and version: Firefox 89
- JupyterLab version: 3.1.0rc2

**Comment by blink1073** [comment]
@meeseeksdev please migrate to jupyterlab/jupyter-renderers
