### PR TITLE
Use `@jupyter/builder` instead of `@jupyterlab/builder`

### PR DESCRIPTION
**Pull request by Darshan808**
## Code changes

- Removed Python-side build scripts that were migrated to the standalone repository: https://github.com/jupyterlab/jupyter-builder  
- Added `@jupyter/builder` as a dependency  
- Retained `@jupyterlab/builder` for compatibility verification  

The compatibility check in `jupyter_builder` currently compares builder versions between core and extensions. Since JupyterLab core does not yet depend on `@jupyter/builder`, the verification logic still relies on `@jupyterlab/builder`. Therefore, it is intentionally kept for now pending further discussion on the migration strategy.

## User-facing changes

None

## Backwards-incompatible changes

- The following commands are deprecated and alisased:
  - `jupyter labextension build`
  - `jupyter labextension watch`
  - `jupyter labextension develop`

- These have been replaced with:
  - `jupyter-builder build`
  - `jupyter-builder watch`
  - `jupyter-builder develop`

## AI usage

No

### CODE REVIEW

**Comment by Darshan808** [comment]
Not sure why but after merging this branch with main, the build started failing with error:
```
       src/renderer.tsx(6,27): error TS2307: Cannot find module '@jupyterlab/ui-components' or its corresponding type declarations.
       src/renderer.tsx(10,26): error TS2307: Cannot find module '@jupyterlab/apputils' or its corresponding type declarations.
       npm error Lifecycle script `build` failed with error:
       npm error code 1
       npm error path /Users/darshan/dev/opensource/jupyterlab/packages/lsp-extension
       npm error workspace @jupyterlab/lsp-extension@4.6.0-alpha.4
       npm error location /Users/darshan/dev/opensource/jupyterlab/packages/lsp-extension
       npm error command failed
       npm error command sh -c tsc -b
       

 >  Lerna (powered by Nx)   Ran target build:all for 6 projects (5s)

    ✔    4/5 succeeded [0 read from cache]

    ✖    1/5 targets failed, including the following:
         - @jupyterlab/lsp-extension:build:all
```

*It was a lockfile issue*

File: jupyterlab/commands.py [hunk 1]
```diff
@@ -1475,8 +1477,8 @@ def _populate_staging(self, name=None, version=None, static_url=None, clean=Fals
 
             # splice the builder as well
             local_path = osp.abspath(pjoin(REPO_ROOT, "builder"))
-            data["devDependencies"]["@jupyterlab/builder"] = local_path
-            target = osp.join(staging, "node_modules", "@jupyterlab", "builder")
+            data["devDependencies"]["@jupyter/builder"] = local_path
+            target = osp.join(staging, "node_modules", "@jupyter", "builder")
```
[the remark this answers is not in the document]
Comment (Darshan808) [reply jupyterlab/commands.py]: I believe we can remove these lines completely as we're planning to remove the `builder` folder.

**Comment by krassowski** [comment]
Can we alias `jupyter labextension build` to `jupyter-builder build` etc for compatibility?

File: scripts/ci_script.sh [hunk 2]
```diff
@@ -241,34 +241,34 @@ if [[ $GROUP == usage ]]; then
...
-    jupyter labextension develop test-hyphens-underscore --overwrite --debug
+    jupyter-builder develop test-hyphens-underscore --overwrite --debug
 
     python -m jupyterlab.browser_check
     jupyter labextension list 1>labextensions 2>&1
     cat labextensions | grep "@jupyterlab/mock-extension.*enabled.*OK"
-    jupyter labextension build extension --static-url /foo/
-    jupyter labextension build extension --core-path ../../../examples/federated/core_package
+    jupyter-builder build extension --static-url /foo/
+    jupyter-builder build extension --core-package-file ../../../examples/federated/core_package/package.json
```
Comment (jtpio) [inline scripts/ci_script.sh:259]: Does this mean the original `--core-path` will not work anymore? Even with the pass-through?

Just thinking about the case where `jupyter labextension build extension --core-path` is still being used.

File: jupyterlab/federated_labextensions.py
Comment (jtpio) [inline jupyterlab/federated_labextensions.py:1]: It seems that some extensions are depending on this file: https://github.com/mwouts/jupytext/blob/e939bf5359be8391ca8ccd4f931385287dc99992/jupyterlab/scripts/install_extension.py#L15

Maybe it's fine it it's only a couple of them as we could open PRs to fix that, but still worth noting.

Comment (krassowski) [reply jupyterlab/federated_labextensions.py:1]: Oh, in that case we should add a shim (re-export this functions from jupyter-builder, with a deprecation warning).

File: scripts/ci_script.sh (hunk 2 above)
Comment (krassowski) [reply scripts/ci_script.sh:259]: Is it used downstream?

Comment (jtpio) [reply scripts/ci_script.sh:259]: Probably not many (not used in notebook, jupyterlite or voila), but there could be some private usage (custom lab based app for instance).

Maybe it could still be worth keeping a compat layer in `jupyter-builder` then, just in case.

Comment (Darshan808) [reply scripts/ci_script.sh:259]: Kept the flag and marked it as deprecated in https://github.com/jupyterlab/jupyter-builder/pull/73. Released in `0.0.4`.

File: docs/source/extension/extension_migration.md
Comment (jtpio) [inline docs/source/extension/extension_migration.md:1]: Probably we could add a proper dedicated section for the 4.6 release to mention the use of `jupyter-builder` for extension authors. But it's also fine if done later in a separate pull request.

File: jupyterlab/federated_labextensions.py [hunk 3]
```diff
@@ -1,483 +1,29 @@
...
-                dest_file = pjoin(dest_dir, file_name)
-                _maybe_copy(src, dest_file, logger=logger)
-    else:
-        src = path
-        _maybe_copy(src, full_dest, logger=logger)
-
-    return full_dest
-
-
-def develop_labextension_py(
```
Comment (jtpio) [inline jupyterlab/federated_labextensions.py:154]: Should we re-expose this one too in the shim?

**Comment by jtpio** [comment]
Also maybe we should remove "and remove @jupyterlab/builder" from the PR title, since it does not remove the package from the repo (yet)?

(mostly for the generated changelog and release notes)

**Comment by krassowski** [comment]
Picked up a conflict from https://github.com/jupyterlab/jupyterlab/pull/18727

File: jupyterlab/federated_labextensions.py (hunk 3 above)
Comment (krassowski) [reply jupyterlab/federated_labextensions.py:154]: If it is easy to do, then yes.

I don't see any use in public code on GitHub though:
 
https://github.com/search?q=develop_labextension_py+NOT+path%3A%2Fdynamic_labextensions.py%2F++NOT+path%3A%2Ffederated_labextensions.py%2F+NOT+path%3A%2Flabextensions.py%2F&type=code
