### ISSUE TITLE
Support Vim Editing Mode in Cells

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#1362]
1. Is it possible to support togging line numbers in cells? The reason is simple. When you have a big chunk of code in Cell and error occurs, you are told on which line the error is but it's for you to locate it quick as there is no line numbers are show for cells. 

2. Is it possible to support toggling vim mode for cells. Vim users will love it.

**Comment by blink1073** [comment]
Hi @dclong, the line numbers can be toggled by pressing `L` in command mode, or in the command palette as shown below.  We do not yet have a Vim mode toggle, do you mind if we rename the issue to reflect that request?


![image](https://cloud.githubusercontent.com/assets/2096628/20866857/dcbdf56c-b9fc-11e6-987c-075ced54b23e.png)

**Comment by dclong** [comment]
@blink1073 
Thank you for the tips! It's so nice to see news features are adding to JupyterLab constantly. Please feel free to rename the issue to better reflect the request.

**Comment by blink1073** [comment]
Cheers!

**Comment by mgwilliams** [comment]
+1

Any update on this?

**Comment by blink1073** [comment]
@mgwilliams, I bumped it to a 1.0 feature parity issue.

**Comment by rlim19** [comment]
+1

**Comment by rainyear** [comment]
+1

**Comment by OliverEvans96** [comment]
:+1: :)

**Comment by stsievert** [comment]
I'd love to see this feature (it's the main reason I do not use jupyterlab).

It certainly *feels* like the cells should support code mirror key bindings since the editor supports them.

**Comment by joelostblom** [comment]
This would be a fantastic addition, thanks for considering it!
There is an addon, [jupyter-vim-bindings](https://github.com/lambdalisue/jupyter-vim-binding), that enables vim bindings for the standalone Jupyer Notebook. It uses the Code Mirror vim implementation (which even let's you define your own keybindings) and it works *really* well! It is the main reason that I am still using the Notebook separately instead of switching to JupyterLab.

**Comment by bulletsweetp** [comment]
+1

Just started using jupyterlab and I love it all except this missing piece

**Comment by jwkvam** [comment]
It seems like it might be a while before the core devs will be able to get to this (no offense to them I know they are very busy). Would anyone be interested in trying to port jupyter-vim-binding to be a jupyterlab plugin? I wouldn't mind taking a stab at it but would appreciate help.

**Comment by ian-r-rose** [comment]
Hi @jwkvam, I'd be happy to provide some guidance/help for this.

How does the `jupyter-vim-binding` handle the fact that notebooks already have a modal editing scheme? That is to say, if I press escape in the notebook, it enters command mode, and I can navigate around the cells, delete them (by pressing `dd` no less), etc. This seems like it would be in conflict with using vim bindings in the notebook.

**Comment by jwkvam** [comment]
@ian-r-rose Thanks! This plugin creates 3 modes, from "outermost" to "innermost": jupyter command, vim command and vim insert. You can run jupyter commands in vim-command mode by pressing `ctrl-o` then the jupyter command. For example to delete a cell in vim-command mode you press `ctrl-o` then `dd`.

It's encouraged that you never enter jupyter command mode. It may seem awkward at first but I grew accustomed to it pretty quickly and now I have more muscle memory hitting ctrl-o that I never enter jupyter command mode. Some jupyter specific things have been added as well. `j` and `k` move up and down lines but `ctrl-j` and `ctrl-k` move up and down cells. So some jupyter commands have snuck into vim commands.

**Comment by joelostblom** [comment]
@ian-r-rose @jwkvam `jupyter-vim-binding` has three modes (from [this discussion](https://github.com/lambdalisue/jupyter-vim-binding/issues/56) started by the author to change mode names):

- Jupyter mode
- Vim mode
    - Command mode
    - Insert mode

`Esc` takes you to vim command mode by default and `Shift` + `Esc` is for Jupyter mode. I believe that the original motivation was to make jupyter mode hard to get to and instead make use of `ctrl` + `o` to execute a single jupyter mode command. Personally I like being able to go into jupyter mode, so I rebound it to `Alt` + `Esc` by configuring [this section](https://github.com/lambdalisue/jupyter-vim-binding/blob/master/vim_binding.js#L68-L74).

**Comment by ian-r-rose** [comment]
Sounds reasonable. It's nice that a lot of the groundwork and experimentation for how to do this has already been done :smile: .

I think that the place to start would be to create a plugin that requires the `INotebookTracker`. An example of this would be the `CellTools` plugin in `notebook-extension/src/index.ts`. Then you can set an event listener for when a new notebook gets created in JupyterLab. When that happens, you will be able to gain access to the CodeMirror instances and patch them up as necessary. I have not had a chance to look through the `jupyter-vim-bindings` implementation, so I don't know exactly what that entails yet.

**Comment by jwkvam** [comment]
@ian-r-rose Awesome, thanks for the pointers! I guess my plan is roughly:

- "Fork" CellTools and see if I can get codemirror vim mode plugin working (that probably breaks jupyterlab).
- Throw the code up in a gist or repo.
- Assuming that works, start to pull in stuff from jupyter-vim-binding.
- I'll use this issue for support and status updates until it's proven.

**Comment by ian-r-rose** [comment]
Awesome! Feel free to ping me on the JupyterLab gitter as well.

**Comment by jwkvam** [comment]
With help from @ian-r-rose got a very early proof of concept going.
repo: https://github.com/jwkvam/jupyterlab_vim
video: https://youtu.be/nry2jocQnvs

**Comment by garyzhalo** [comment]
@jwkvam Great work! When I tried to install this extension, it shows that "jupyterlab_vim" is not a valid npm package. Any ideas?

**Comment by jwkvam** [comment]
@garyzhalo Sorry about that. I haven't published anything yet so I would recommend cloning the repo and doing a dev install. I tried to update the readme to reflect that.

**Comment by jwkvam** [comment]
One last announcement. I cut a first release! You can give it a shot by running:
```
jupyter labextension install jupyterlab_vim
```

**Comment by dclong** [comment]
@jwkvam 
Great news! Will give it a try later.

**Comment by blink1073** [comment]
@jwkvam, well done!  I'm not a vim user, but I took it for a spin and it looks great!

**Comment by bulletsweetp** [comment]
```
$ jupyter labextension install jupyterlab_vim
...
"jupyterlab_vim@0.1.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=0.11.1-0 <0.12.0-0    >=0.13.0-0 <0.14.0-0 @jupyterlab/application
>=0.11.1-0 <0.12.0-0    >=0.13.0-0 <0.14.0-0 @jupyterlab/notebook
```

```
$ pip show jupyterlab
Name: jupyterlab
Version: 0.28.14
Summary: An alpha preview of the JupyterLab notebook server extension.
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.com
License: BSD
Location: /usr/local/lib/python2.7/site-packages
Requires: notebook, jupyterlab-launcher
```

**Comment by jwkvam** [comment]
@bulletsweetp Ah yea, I'll have to put that in the readme. It only works with Jupyterlab 0.30.x. Until Jupyterlab hits 1.0, I'll be trying to keep the latest plugin working with the latest version of Jupyterlab. Sorry for the inconvenience, I think this is true of all extensions.

**Comment by bulletsweetp** [comment]
oh my bad, I thought I had the latest!

**Comment by stsievert** [comment]
@jwkvam thanks for developing this plugin! I've found I'm more likely to use Jupyterlab now thanks to your plugin.

**Comment by rl1m** [comment]
Thanks for developing the extension. It would be very awesome to have vim on-board with jupyter lab.

I tried to install on jupyter lab --version, 0.30.6. Unfortunately, I got this error message:

> '' pack jupyterlab_vim
'NoneType' object has no attribute 'rfind'

Any guidance please.

Thanks in advance and cheeers

**Comment by blink1073** [comment]
Hi @rl1m, that error message will be better in the next version.  I means that you need to install nodejs: https://nodejs.org/en/download/.

**Comment by omrihar** [comment]
Hi @jwkvam, thanks for the extension! I just started playing again with JupyterLab and found this thread through the original jupyter notebook vim plugin.

Do you plan to have this be an exact port of vim-bindings? In that case I noticed that
1. ctrl+o d deletes a cell instead of dd
2. ctrl+o o works (add cell after) but ctrl+o O (add cell before) doesn't work.

Thanks for the great work!
Omri

**Comment by jwkvam** [comment]
@omrihar I'm not too concerned with creating an exact clone, but I do like it's overall UX so I'm generally following it's path but I've made a couple exceptions so far which you've noticed :) There are issues for both of the points you raise.

1. https://github.com/jwkvam/jupyterlab_vim/issues/9
2. https://github.com/jwkvam/jupyterlab_vim/issues/6

**Comment by ASpeiser** [comment]
What would be needed to do the same for sublime keybindings?
Do get them for the notebook didn't require an extension, I just followed: http://blog.rtwilson.com/how-to-get-sublime-text-style-editing-in-the-ipythonjupyter-notebook/

**Comment by blink1073** [comment]
Hi @ASpeiser, it is currently not possible to change the `keyMap`, because we are using a generic interface for editors, and not all editors support a named key map (e.g. monaco).   Right now it would take a plugin similar to the vim plugin to change the keymap.

**Comment by benlindsay** [comment]
+1 to this effort. Lack of vim bindings in notebooks is the one thing keeping me from using JupyterLab

**Comment by vyzyv** [comment]
If anyone stumbles on this thread you can (I guess, not tested thouroughly) edit notebooks directly in Vim/Neovim using this plugin **[vyzyv/vimpyter](https://github.com/vyzyv/vimpyter)** (sorry for plug but I thought you may find it useful).

**Comment by claytontstanley** [comment]
Given that it seems the vim plugin for the editor has three modes (insert, command, jupyter), are we talking about four for the notebooks? (insert, command, cell, jupyter) or can the last two be combined? I’m just starting out with Jupyter Lab so it may be a dumb question, but I certainly noticed the lack of command mode within a cell for a notebook.

**Comment by benlindsay** [comment]
@claytontstanley The vim plugin for plain jupyter notebooks (https://github.com/lambdalisue/jupyter-vim-binding) has insert, command, and jupyter modes. I've only played around a little with the Jupter Lab editor, but I don't see how to enter Jupyter mode in there and I'm not sure what that would do. Unless there's something I'm missing, all I'd want from vim bindings enabled for Jupyter Notebooks within Jupyter Lab is the same 3 modes enabled in plain Jupyter Notebooks, i.e. insert (normal typing within a cell), command (navigation within a cell, but where j/k navigation can continue into adjacent cells), and Jupyter mode (like command mode but navigating between cells)

**Comment by claytontstanley** [comment]
Yes @benlindsay something like that where there’s three and not four modes seems sensible. The jk to get out from within a cell is interesting, because what would you want if you accidentally go one row too far and get out of the cell, but then want to go back? You couldn’t then go back into the cell with jk because you’d be in Jupyter mode at that point. You could alternatively trap jk at the upper and lower points and use another key binding to move one mode up explicitly, as needed.

**Comment by benlindsay** [comment]
@claytontstanley The behavior I was trying to describe isn't anything new, it's just what's already implemented in the jupyter-vim-binding plugin. If you're in command mode at the top of a cell and push 'k', it goes to the bottom of the cell above it but leaves you in command mode rather than switching to Jupyter mode. That functionality isn't super important to me but would be nice if it can be implemented. Most other navigation commands operate just within the cell and don't allow travel outside the cell (i.e. selections with v, V, or CTRL-V have to stay within a cell, g and GG stay within a cell etc.)

**Comment by benlindsay** [comment]
@claytontstanley I feel kind of dumb for not catching this above, but there is a working vim bindings plugin with enough functionality to convince me to transfer to Jupyter Lab, so if you didn't catch that already go check out https://github.com/jwkvam/jupyterlab_vim

**Comment by jpribyl** [comment]
This is amazing, it even does macros! Thank you SO much!!

**Comment by davidbrochart** [comment]
As @claytontstanley mentioned, the [jupyterlab-vim](https://github.com/jwkvam/jupyterlab-vim) plugin is great for enabling CodeMirror vim bindings, which is enough for most users. But I was wondering if JupyterLab would allow editing cells with [vim.wasm](https://github.com/rhysd/vim.wasm), which is the original Vim code ported to WebAssembly.

**Comment by jasongrout** [comment]
Closing since the [jupyterlab-vim](https://github.com/jwkvam/jupyterlab-vim) plugin seems to fulfill the need mentioned in the OP.

@davidbrochart - that sounds like an interesting idea for another plugin!
