### PR TITLE
Ship vega4-extension by default

### LINKED ISSUE #6572: Ship vega4-extension by default
I brought this up at the end of https://github.com/jupyterlab/jupyterlab/issues/6402, but given that this is really a separate action item from that original issue, I'm opening a new issue here.

I think jupyterlab 1.0.0 should ship the three extensions I mentioned in the title out-of-the box, in addition to the vega5-extension that is already included by default. I think ideally this issue here should be added to the 1.0.0 milestone.

Without that, users will experience a major regression when they update to jupyterlab 1.0.0: all notebooks that they created with earlier versions of jupyterlab that include vega or vega-lite figures will no longer display properly when opened in jupyterlab 1.0.0. I feel that experience would be incompatible with the promise that was made last spring that juptyerlab was ready for end users for their daily work. That messaging implied (to me at least) that minimally I would be able to open files in jupyterlab 1.0.0 that I created with vanilla juptyerlab 0.35.x and they would display correctly.

I believe this affects minimally Python and Julia users: Python users that used altair in their notebooks, and Julia users that used VegaLite.jl. I don't have numbers, but it seems to me that both packages were quite popular over the last year, so this doesn't strike me as a corner case/small user group that would be affected.

This would also be in line with what nteract is doing with their support for vega and vega-lite out-of-the-box.

I don't know how complicated this would be, and I do understand that it is late in the release process for jupyterlab 1.0.0... But on the other hand, I think from an end-user point of view this is really a major regression/bug. But maybe this wouldn't be so complicated to fix? Might it be enough to just move the existing code for vega2-extension, vega3-extension and vega4-extension from https://github.com/jupyterlab/jupyter-renderers into this repository here? And add them to a few config places so that they get shipped out-of-the-box?

Pinging @domoritz and @jakevdp from the vega, vega-lite and altair side of things. Not sure who from the jupyterlab team would be the right point person?

### PR DESCRIPTION
**Pull request by domoritz**
Fixes #6572

### CODE REVIEW

**Comment by ian-r-rose** [comment]
I think I've gotten myself a bit confused. If both extensions only import `vega-embed`, and the same version of that library is used, then how do they determine which versions of `vega`/`vega-lite` should be used?

**Comment by domoritz** [comment]
The vega4 package [depends on a different version of Vega and Vega-Lite](https://github.com/jupyterlab/jupyterlab/pull/6591/files#diff-b90028e8f8127d5ca1b3b5c763f78b3dR40). I was hoping that that would be sufficient. Vega-Embed does not depend on Vega or Vega-Lite directly. Instead, they are [specified as peer dependencies](https://github.com/vega/vega-embed/blob/2b55b25e4f38527ec28cf90ac3c1abf669162a13/package.json#L76).

**Comment by domoritz** [comment]
Does Jupyterlab allow multiple versions of the same package at the same time? If not, we may need an alias release `vega4` or something.

**Comment by ellisonbg** [comment]
See recent comments on #6572 - I think we are converging on this being a good idea, but it looks like there are still details to work out. I too am confused on how this will work as `vega-embed` doesn't seem to have a way to know which version of vega and vega-lite to use.

**Comment by domoritz** [comment]
Vega-Embed now uses peer dependencies. This means that Vega and Vega-Lite have to be installed but it doesn't depend on specific versions.

**Comment by saulshanabrook** [comment]
@domoritz yep that makes sense. We depend on the the version of vega and vega-lite now in the vega extension. This is currently failing some tests. I am going to work on this locally to try to get it working and test it.

**Comment by saulshanabrook** [comment]
@domoritz  I have made some progress here, but I am having an issue I think because vega-lite 2.6.0's dependency on vega-util is too broad https://github.com/vega/vega-lite/blob/v2.6.0/package.json#L116 It depends on `^1.7.0` which means `1.10.0` is allowed and I think that version has breaking changes? It's giving me some typescript errors trying to build with `vega-lite` 2.6.0 and that version of `vega-util`:


```
../../node_modules/vega-lite/build/src/log.d.ts:23:5 - error TS2416: Property 'level' in type 'LocalLogger' is not assignable to the same property in base type 'LoggerInterface'.
  Type '() => this' is not assignable to type '(_: number) => number | LoggerInterface'.
    Type 'this' is not assignable to type 'number | LoggerInterface'.
      Type 'LocalLogger' is not assignable to type 'number | LoggerInterface'.
        Type 'LocalLogger' is not assignable to type 'LoggerInterface'.
          Type 'this' is not assignable to type 'LoggerInterface'.
            Property 'error' is missing in type 'LocalLogger' but required in type 'LoggerInterface'.

23     level(): this;
       ~~~~~

  ../../node_modules/vega-util/index.d.ts:140:3
    140   error(...args: any[]): LoggerInterface;
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'error' is declared here.

../../node_modules/vega-lite/build/src/log.d.ts:24:5 - error TS2416: Property 'warn' in type 'LocalLogger' is not assignable to the same property in base type 'LoggerInterface'.
  Type '(...args: any[]) => this' is not assignable to type '(...args: any[]) => LoggerInterface'.
    Type 'this' is not assignable to type 'LoggerInterface'.

24     warn(...args: any[]): this;
       ~~~~

../../node_modules/vega-lite/build/src/log.d.ts:25:5 - error TS2416: Property 'info' in type 'LocalLogger' is not assignable to the same property in base type 'LoggerInterface'.
  Type '(...args: any[]) => this' is not assignable to type '(...args: any[]) => LoggerInterface'.
    Type 'this' is not assignable to type 'LoggerInterface'.

25     info(...args: any[]): this;
       ~~~~

../../node_modules/vega-lite/build/src/log.d.ts:26:5 - error TS2416: Property 'debug' in type 'LocalLogger' is not assignable to the same property in base type 'LoggerInterface'.
  Type '(...args: any[]) => this' is not assignable to type '(...args: any[]) => LoggerInterface'.
    Type 'this' is not assignable to type 'LoggerInterface'.

26     debug(...args: any[]): this;
       ~~~~~
```

In the mentioned `log.d.ts`, we have:

```
export { LoggerInterface } from 'vega-util';
/**
 * Logger tool for checking if the code throws correct warning
 */
export declare class LocalLogger implements LoggerInterface {
    warns: any[];
    infos: any[];
    debugs: any[];
    level(): this;
    warn(...args: any[]): this;
    info(...args: any[]): this;
    debug(...args: any[]): this;
}
```

which looks like it is missing an `error` method?

**Comment by saulshanabrook** [comment]
I opened a PR against this branch which gets things working locally for me: https://github.com/domoritz/jupyterlab/pull/1

**Comment by saulshanabrook** [comment]
In my branch, outputs of both version work: https://gist.github.com/saulshanabrook/97c28550ab12e684adc3c325038537ce

**Comment by ian-r-rose** [comment]
@saulshanabrook Does it correctly delegate to the right extension? That is, does v2 go to the vega4-extension, and v3 go to the vega5-extension? Or is it just delegating to one of them that happens to be able to render both schemas?

If it is delegating correctly, I'd be curious to do some debugger tracing to see how that dispatch is actually happening, since I don't understand it just yet.

**Comment by domoritz** [comment]
https://github.com/jupyterlab/jupyterlab/pull/6591#issuecomment-503780690 should be fixed in Vega-Lite 2.7, which I just released.

**Comment by saulshanabrook** [comment]
I have this working now.

> Does it correctly delegate to the right extension? That is, does v2 go to the vega4-extension, and v3 go to the vega5-extension? Or is it just delegating to one of them that happens to be able to render both schemas?

@ian-r-rose I open up the chrome debugger, go to sources and find the packages:

Screen Shot 2019-06-20 at 7 33 09 PM

One vega-embed is hosted to the top level `node_modules` and another remains under the `vega5-extesion` package in the `node_modules`. I went into each of those, and found the `vega-lite` inside of them. I set breakpoints in a file in each of those vega lite sources and verified that those breakpoints were hit when rendering each version of the Vega spec.

Screen Shot 2019-06-20 at 7 30 18 PM

@domoritz I ended up having to depend on different `vega-embed` versions in the different extensions. For some reason, if they were the same version I couldn't get webpack to not just load one version of `vega-lite`. I opened https://github.com/jupyterlab/jupyterlab/issues/6675 to track this in the future, but at least this is working for now.

---

This also changes a few things about our build system that were required to get this working.

1. Add `@jupyterlab/vega*-extension/vega*/**` to the [workspaces `nohoist`](https://yarnpkg.com/blog/2018/02/15/nohoist/) so that all vega packages, and their dependencies, which are in the vega extensions, will not be hoisted by yarn. You can verify this now by running `yarn why vega-lite`. You will see there are two versions installed, neither of which are in the root.
2. Add a list of packages in buildutils that can have differing versions between packages. Otherwise, it will go ahead and change them for us to make them all the same.
3. Switch the buildutils to find the workspaces packages at `workspaces.packages` instead of `workspaces` so `workspaces` is now an object with a `nohoist` key as well as a `packages` key instead of the packages list
4. Update how we load a packages `package.json` in the `buildutils`, so that this works for packages that are not hoisted.
5. Switch out CSS to be included in a file, via `mini-css-extract-plugin`, instead of inline. This is helpful for debugging (we can see what original file a style comes from) and is also probably better for browser performance. We were already doing this for themes. We also don't split this file into chunks, because when it was split into chunks the order was messing up some CSS ordering.
6. Rename the document widget factories for vega and vega lite, so they are suffixed with their version and don't conflict with each other

**Comment by jasongrout** [comment]
@saulshanabrook 

```diff
diff --git a/dev_mode/webpack.config.js b/dev_mode/webpack.config.js
index 7b39c2f89..3d96ad045 100644
--- a/dev_mode/webpack.config.js
+++ b/dev_mode/webpack.config.js
@@ -128,8 +128,7 @@ const plugins = [
   new webpack.HashedModuleIdsPlugin(),
   new JupyterFrontEndPlugin({}),
   new MiniCssExtractPlugin({
-    filename: '[name].css',
-    chunkFilename: '[id].css'
+    filename: '[name].[chunkhash].css',
   })
 ];

```

**Comment by jasongrout** [comment]
Thanks. Your examples above work, and things look good.

**Comment by saulshanabrook** [comment]
Thanks again @domoritz for releasing a new version of Vega Lite to help with this!

**Comment by davidanthoff** [comment]
Yeah, thanks so much to everyone!

**Comment by blink1073** [comment]
CSS extraction only works with themes because the server is mangling the css to handle paths: https://github.com/jupyterlab/jupyterlab_server/blob/a81dea3a25a473374051b1fada08bd76db965577/jupyterlab_server/themes_handler.py#L46
We need a dynamic webpack public url because base_url is set at run time

**Comment by blink1073** [comment]
The extractor supports a function for public path, that could be made to work: https://github.com/webpack-contrib/mini-css-extract-plugin#publicpath

**Comment by vidartf** [comment]
@saulshanabrook Does all this custom code in buildutils mean that third-party extensions will not be able to accomplish such a side-by-side setup?

**Comment by vidartf** [comment]
(Trying to ensure we stick to our promise that core extensions are not "special" in any way)

**Comment by jasongrout** [comment]
> The extractor supports a function for public path, that could be made to work: https://github.com/webpack-contrib/mini-css-extract-plugin#publicpath

Is the idea here that the public path function relies on a base url from the page config?

**Comment by jasongrout** [comment]
> Is the idea here that the public path function relies on a base url from the page config?

I guess what I said doesn't make sense, since the public path function is run at webpack compile time, not runtime: https://github.com/webpack-contrib/mini-css-extract-plugin/blob/392c4ae68c9384230d6652e7fee277a702deacd7/src/loader.js#L75

**Comment by jasongrout** [comment]
> @saulshanabrook Does all this custom code in buildutils mean that third-party extensions will not be able to accomplish such a side-by-side setup?

IIRC, all of the buildutils here are integrity checks on our own packages, not necessary things that all packages need.

**Comment by blink1073** [comment]
Ah, right. It could be that we need to use a separate endpoint for known extracted css that uses the same logic as the theme loader. That is yet another asset class that can't be put on a cdn then...

**Comment by jasongrout** [comment]
Interestingly, looking at the generated css, the only urls seem to be inlined data urls, and things that look like this for the fonts that are beside the css file:

```
@font-face {
  font-family: "Icons16";
  font-weight: normal;
  font-style: normal;
  src: url({{page_config.fullStaticUrl}}/6fdb722c94434811f89a68eafc4531f8.eot?#iefix) format("embedded-opentype"), url({{page_config.fullStaticUrl}}/cd1a26696ebf17a89545a3f9067d7028.woff) format("woff"), url({{page_config.fullStaticUrl}}/5fa1b8f25b4aa8787f70d5b6b7f0b90f.ttf) format("truetype"); }
```
which is coming from setting the webpack config at https://github.com/jupyterlab/jupyterlab/blob/dcfe0ba40d5bd1e4ab57cbb927a10ffe3dedf416/dev_mode/webpack.config.js#L147

Perhaps we just need to treat that css file as a template?

**Comment by blink1073** [comment]
We could, but that would still mean a separate tornado handler and prevents using a static server like cdn or nginx from serving the CSS.

**Comment by jasongrout** [comment]
True. How did it work before this with the font paths? Even with the css bundled into the js, the fonts were separate files, right?

**Comment by blink1073** [comment]
They've always been separate files, yes. I don't follow what you mean though.  If you mean before this PR, they were loaded dynamically by webpack using the webpack public path

**Comment by jasongrout** [comment]
In the js, somehow that public path gets set to something like `/lab/static/`, i.e., the `'{{page_config.fullStaticUrl}}/'` is resolved. Do you know who does that resolution?

**Comment by saulshanabrook** [comment]
> Does all this custom code in buildutils mean that third-party extensions will not be able to accomplish such a side-by-side setup?

Currently it requires people distributing JupyterLab to also have the `nohoist` argument added to their `package.json`. Or maybe not *require*, just that's the only way I got our webpack to pick up things properly. With another build system, it might resolve the paths in a slightly different manner.

But your question got me thinking, and maybe it would be best to prebuild the `vega` dependencies in each of the extensions into a seperate bundle, then those bundles get published with the packages, so that anyone who installs the extension doesn't have to worry about the dependency resolution.

**Comment by jasongrout** [comment]
> then those bundles get published with the packages, so that anyone who installs the extension doesn't have to worry about the dependency resolution.

Then you have to be careful about deduplicating the packages that need deduplication, like phosphor, etc.

**Comment by saulshanabrook** [comment]
> Then you have to be careful about deduplicating the packages that need deduplication, like phosphor, etc.

I will just bundle the `vega-embed` import that captures `vega-lite` and `vega` as well. Then the main extension will import that, just as it was importing `vega-embed`, but now it will just be one big JS file.

**Comment by jasongrout** [comment]
To be fair, we couldn't serve the css before because it was bundled in the js :)

**Comment by blink1073** [comment]
If that {{}} is in the served JS then it is a bug. It should only be in index.html, from the template file.

**Comment by saulshanabrook** [comment]
If we build jupyterlab with a previous commit, we see the CSS is all embedded in the JS, for example in the `vendors.js` file:

```javascript
/***/ "S7FT":
/*!***********************************************************************!*\
  !*** ../node_modules/@blueprintjs/icons/resources/icons/icons-16.eot ***!
  \***********************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

module.exports = __webpack_require__.p + "3326c360137c2d6a6909d0c4303e502a.eot";
```

I don't understand yet how the server was previously mangling the CSS paths.

In the generated `index.html`, I see the `base_url` being inserted in the page config and to access the favicons, and the `page_config.fullStaticUrl` being used to get the URL to the JS file. I am trying to understand how that affected the URLs to the fonts.

**Comment by blink1073** [comment]
We were setting the webpack public path dynamically in dev_mode/index.js

**Comment by blink1073** [comment]
https://github.com/jupyterlab/jupyterlab/blob/a8e4af95044855a2b561a6bf67c81ccb57b17d2c/dev_mode/index.js#L13

**Comment by saulshanabrook** [comment]
Ah I see, thank you. OK well in my current branch, I can try to bundle the vega dependencies separately and switch back to the old way of loading CSS

**Comment by jasongrout** [comment]
That sounds great. If that doesn't work, then perhaps we revert back to only providing vega 5.

**Comment by jasongrout** [comment]
Looks like we should have read this comment right after the public path setting: https://github.com/jupyterlab/jupyterlab/blob/a8e4af95044855a2b561a6bf67c81ccb57b17d2c/dev_mode/index.js#L15-L16

**Comment by blink1073** [comment]
I tried to help.  😉

**Comment by jasongrout** [comment]
I think fixing this issue is probably the last breaking thing before the rc.

**Comment by jasongrout** [comment]
I've made https://github.com/jupyterlab/jupyterlab/issues/6684 about fixing this problem, so we have a record of the issue.
