### ISSUE TITLE
node_modules/@jupyterlab/codeeditor/lib/editor.d.ts:47:15 - error TS2411: Property 'toJSON' of type '() => any' is not assignable to 'string' index type 'JSONValue'.

### ISSUE THREAD

**Issue by lidongze0629** [jupyterlab/jupyterlab#12330]
I am trying to compile a JupyterLab extension but running into the following error:

### What is actually happening?

build failed with `node_modules/@jupyterlab/codeeditor/lib/editor.d.ts:47:15 - error TS2411: Property 'toJSON' of type '() => any' is not assignable to 'string' index type 'JSONValue'.`

![截屏2022-04-02 下午7 56 15](https://user-images.githubusercontent.com/23491543/161382073-d36eae5c-61bd-4a07-87b5-73776e830aef.png)

### What is expected?

build successfully in typescript > 4.4.0 (4.6.3)

| Environment | Info |
| --- | --- |
| React | react@17.0.2  react-native@0.68.0 typescript@4.6.3 |
| System | MacOS BigSur 11.6.2 |
| Browser | chrome |

---
It works under typescript < 4.4.0, but failed > 4.4.0 (4.6.3), can somebody help how to make it work with typescript> 4.4.0

**Comment by jweill-aws** [comment]
This interface was updated to work with TypeScript 4.5 in pull request #11594. This was merged into the `master` branch which is for JupyterLab 4.0. This fix is not backward compatible with JupyterLab 3.3.x or 3.4.x and will not be backported. Are you developing against 4.0/master? If you intend to develop for JupyterLab 3, you will need to use TypeScript ≤ 4.4.0.

**Comment by jweill-aws** [comment]
Closed this issue for lack of information. If you still need help with this, please reopen it and provide the info requested. Thanks for your contribution!
