### ISSUE TITLE
Terminal theme option should not be available if terminal feature is disabled 

### ISSUE THREAD

**Issue by Mithil467** [jupyterlab/jupyterlab#10879]
## Description

Terminal feature was disabled by default for me. This is the output I get in the console.
![image](https://user-images.githubusercontent.com/41439841/130236456-cb547e61-fd4c-40cc-976a-914c28980efe.png)

But still I can see the `Terminal Theme` option under Settings.
![image](https://user-images.githubusercontent.com/41439841/130236303-06ec1906-7abe-491b-b947-93113bdaa679.png)

Further, clicking it does not provide any list of themes.

## Reproduce

1. Click on Settings.
2. You can see the Terminal Theme option.
3. Try clicking on it. Nothing happens.

## Expected behavior

The `Terminal Theme` option should not be available if the Terminal feature is disabled.

## Context

- Operating System and version: Windows 10
- Browser and version: Chrome 92
- JupyterLab version: Latest source from  master  (https://github.com/jupyterlab/jupyterlab/commit/0820455e14586e75b27fc2de80ce30683ce6d7a7)

Browser output -
```
Disabling terminals plugin because they are not available on the server.
```

**Comment by Mithil467** [comment]
The check for terminal feature being enabled or not is done here -
https://github.com/jupyterlab/jupyterlab/blob/68a6066dc03dc7cc76141ae78e945faf99da5205/packages/terminal-extension/src/index.ts#L95-L100

Here we have some info about how to remove the added menu option. https://github.com/jupyterlab/jupyterlab/pull/10254#issuecomment-845490123 
It says to set the widget parent to `null`. Is this the correct direction to solve this issue?

**Comment by Mithil467** [comment]
I tried doing this
```js
var x = mainMenu?.settingsMenu.items.find( 
        item =>
          item.type === 'submenu' &&
          item.submenu?.id === 'jp-mainmenu-settings-terminaltheme'
      );
console.log(x);
```
Which gave me this output
![image](https://user-images.githubusercontent.com/41439841/130655792-63210d30-017f-4e3f-a08a-7a2320cf79f2.png)

**Comment by krassowski** [comment]
This looks like a regression introduced in #10373. The `terminal-extension` bails if it finds no terminals available, which previously meant that no menus were added, but now the menus are added whether it bails or not. @fcollonval is there a way for an extension to stop the transformation of its settings once it is loaded, or do we need to use the old API to remove the menu post-hoc as @Mithil467 is currently exploring?


@Mithil467 once you got the item, you can try to call [`Menu.removeItem`](https://jupyterlab.github.io/lumino/widgets/classes/menu.html#removeitem), which I guess would be `mainMenu?.settingsMenu.removeItem(x)` in this case?

**Comment by Mithil467** [comment]
The above fix is giving this error - `Property 'removeItem' does not exist on type 'ISettingsMenu'`

**Comment by fcollonval** [comment]
@Mithil467 Could you update the following line:

https://github.com/jupyterlab/jupyterlab/blob/0aed1cca194f5724d95c7d7896682eaacb8be925/packages/ui-components/src/components/menu.ts#L16

To 

```ts
export interface IRankedMenu extends Menu {
```

Then it should work.

**Comment by Mithil467** [comment]
Thank you! @fcollonval @krassowski 
I have done the required fixes in this PR.
