### ISSUE TITLE
New target in 3.6.0 induces downstream error

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#13913]
FYI, I think this caused our builds to fail with:

```
node_modules/@jupyterlab/services/lib/event/index.d.ts(89,52): error TS2583: Cannot find name 'AsyncIterable'. Do you need to change your target library? Try changing the `lib` compiler option to 'es2018' or later.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

_Originally posted by @maartenbreddels in https://github.com/jupyterlab/jupyterlab/issues/13052#issuecomment-1413919481_

The change was introduced by https://github.com/jupyterlab/jupyterlab/pull/13465

**Comment by fcollonval** [comment]
I'm lookiing at reverting the change
