### ISSUE TITLE
Failed to instantiate the extension manager pypi

### ISSUE THREAD

**Issue by fabltd** [jupyterlab/jupyterlab#17012]
## Description

The following error occours on start up:

```
 Failed to instantiate the extension manager pypi. Falling back to read-only manager.
    Traceback (most recent call last):
      File "/home/x/Dev/jupyter/lib/python3.12/site-packages/jupyterlab/labapp.py", line 837, in initialize_handlers
        ext_manager = manager_factory(app_options, listings_config, self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/x/Dev/jupyter/lib/python3.12/site-packages/jupyterlab/extensions/__init__.py", line 46, in get_pypi_manager
        return PyPIExtensionManager(app_options, ext_options, parent)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/x/Dev/jupyter/lib/python3.12/site-packages/jupyterlab/extensions/pypi.py", line 134, in __init__
        self._httpx_client = httpx.AsyncClient(proxies=proxies)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: AsyncClient.__init__() got an unexpected keyword argument 'proxies'
```

This is a fresh installation. Using pip install 

## Reproduce

- sudo apt install python3-venv -y
- python3 -m venv jupyter_env
- source jupyter_env/bin/activate
- pip install jupyter
- Run Configure commands 

Finally run 

- jupyter notebook

The error is presented in the console

- Operating System and version: 

Ubuntu 24.04.1 LTS

- JupyterLab version: 

Selected Jupyter core packages...
IPython          : 8.29.0
ipykernel        : 6.29.5
ipywidgets       : 8.1.5
jupyter_client   : 8.6.3
jupyter_core     : 5.7.2
jupyter_server   : 2.14.2
jupyterlab       : 4.2.6
nbclient         : 0.10.0
nbconvert        : 7.16.4
nbformat         : 5.10.4
notebook         : 7.2.2
qtconsole        : not installed
traitlets        : 5.14.3

**Comment by krassowski** [comment]
This is due to a new release of `httpx` (20 hours ago). Installing `httpx<0.28.0` should solve it. We will release patched versions that work with 0.28.0 after merging https://github.com/jupyterlab/jupyterlab/pull/17013.

For contributors: note that this is also seen on CI with failing visual regression tests:

```
    [jupyterlab] › test/jupyterlab/sidebars.test.ts:42:9 › Sidebars › Open Sidebar tab extensionmanager.main-view 
    [jupyterlab] › test/jupyterlab/sidebars.test.ts:262:9 › Sidebar keyboard navigation @a11y › Open accordion panels extensionmanager.main-view via keyboard navigation 
```

and

```
Notice:   7 failed
    [documentation] › test/documentation/extension_manager.test.ts:54:7 › Extension Manager › Sidebar 
    [documentation] › test/documentation/extension_manager.test.ts:63:7 › Extension Manager › Warning 
    [documentation] › test/documentation/extension_manager.test.ts:72:7 › Extension Manager › Warning acknowledge 
    [documentation] › test/documentation/extension_manager.test.ts:82:7 › Extension Manager › Search 
    [documentation] › test/documentation/extension_manager.test.ts:106:7 › Extension Manager › Update button 
    [documentation] › test/documentation/extension_manager.test.ts:130:7 › Filtered Extension Manager › Blocked installed extension 
    [documentation] › test/documentation/extension_manager.test.ts:157:7 › Filtered Extension Manager › Allowed installed extension 
```

**Comment by absognety** [comment]
> This is due to a new release of `httpx` (20 hours ago). Installing `httpx<0.28.0` should solve it. We will release patched versions that work with 0.28.0 after merging #17013.
> 
> For contributors: note that this is also seen on CI with failing visual regression tests:
> 
> ```
>     [jupyterlab] › test/jupyterlab/sidebars.test.ts:42:9 › Sidebars › Open Sidebar tab extensionmanager.main-view 
>     [jupyterlab] › test/jupyterlab/sidebars.test.ts:262:9 › Sidebar keyboard navigation @a11y › Open accordion panels extensionmanager.main-view via keyboard navigation 
> ```
> 
> and
> 
> ```
> Notice:   7 failed
>     [documentation] › test/documentation/extension_manager.test.ts:54:7 › Extension Manager › Sidebar 
>     [documentation] › test/documentation/extension_manager.test.ts:63:7 › Extension Manager › Warning 
>     [documentation] › test/documentation/extension_manager.test.ts:72:7 › Extension Manager › Warning acknowledge 
>     [documentation] › test/documentation/extension_manager.test.ts:82:7 › Extension Manager › Search 
>     [documentation] › test/documentation/extension_manager.test.ts:106:7 › Extension Manager › Update button 
>     [documentation] › test/documentation/extension_manager.test.ts:130:7 › Filtered Extension Manager › Blocked installed extension 
>     [documentation] › test/documentation/extension_manager.test.ts:157:7 › Filtered Extension Manager › Allowed installed extension 
> ```
> 
> Also `Linux (python, 3.9)`, `Linux (python, 3.13)`, and `Install from SDist and Test` fail for the same reason.

Worked like a charm!! Thanks.

**Comment by krassowski** [comment]
JupyterLab [`v4.3.2`](https://github.com/jupyterlab/jupyterlab/releases/tag/v4.3.2) was just released and includes a fix and pins httpx to `~=0.28.0` to avoid similar surprises in the future.
