### PR TITLE
Upgrade to Typescript 4

### PR DESCRIPTION
**Pull request by jasongrout**
## Code changes

Upgrades to Typescript 4 and fixes a few resulting compilation errors.

### CODE REVIEW

**Comment by jasongrout** [comment]
I made the mistake of trying to upgrade Typedoc. However, we rely on a specific prerelease of an old release of typedoc for the "library" mode. If we want to upgrade typedoc, we'll have to change the mode from library to file or module at https://github.com/jupyterlab/jupyterlab/blob/d18ea92175d2b10a2fc777c67b3eecf10125f120/typedoc.js#L27

I pinned the specific prerelease version of typedoc that provides this library mode so it doesn't cause us upgrade problems in the future (instead of just pulling in typedoc@next).

See https://github.com/TypeStrong/typedoc/pull/1184#issuecomment-653239597

**Comment by blink1073** [comment]
Note: docmanager test was broken by #8888, Gonzalo is going to make a follow-on PR today.

**Comment by blink1073** [comment]
Lint errors all appear to be related to DOM API lib changes, e.g.

```
/home/runner/work/jupyterlab/jupyterlab/packages/docmanager/src/pathstatus.tsx
  0:0  error  Parsing error: Cannot read property 'map' of undefined
```

**Comment by jasongrout** [comment]
docmanager test appears to be failing because ts-jest does not yet claim support for ts 4.0. This was merged in https://github.com/kulshekhar/ts-jest/issues/1887 and will apparently be released this week.

**Comment by jasongrout** [comment]
> Lint errors all appear to be related to DOM API lib changes, e.g.

@blink1073 - what gave you the idea that this is related to DOM API lib changes? As far as I can tell, this is a problem with the eslint parser somehow.

**Comment by blink1073** [comment]
I didn't dig deeply, just the fact that it was widespread and the same property given the backwards incompatibility warning in their release noted.

**Comment by jasongrout** [comment]
Ah, thanks. It does seem that typescript-eslint needs to be upgraded to support ts4. Looking into it.

**Comment by jasongrout** [comment]
> docmanager test appears to be failing because ts-jest does not yet claim support for ts 4.0. This was merged in [kulshekhar/ts-jest#1887](https://github.com/kulshekhar/ts-jest/issues/1887) and will apparently be released this week.

Sorry, that seems to just be a warning, not a failure.

**Comment by blink1073** [comment]
After we merge https://github.com/jupyterlab/jupyterlab/pull/8894 let's make sure the tests pass here.

**Comment by jasongrout** [comment]
I rebased on #8894.
