### ISSUE TITLE
Enabled labextensions break CodeMirror syntax highlighting, shortcuts, etc.

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyterlab#1339]
The issue looks like:

![image](https://cloud.githubusercontent.com/assets/512354/20779553/11b1d49e-b72a-11e6-84a7-a76ce0863a61.png)

I was able to get syntax highlighting and other CM features back by disabling all of my installed extensions:

```
jupyterlab_json disabled: /Users/grant/anaconda/share/jupyter/labextensions/jupyterlab_json
jupyterlab_plotly disabled: /Users/grant/anaconda/share/jupyter/labextensions/jupyterlab_plotly
jupyterlab_react disabled: /Users/grant/anaconda/share/jupyter/labextensions/jupyterlab_react
jupyterlab_table disabled: /Users/grant/anaconda/share/jupyter/labextensions/jupyterlab_table
jupyterlab_widgets disabled : /Users/grant/anaconda/share/jupyter/labextensions/jupyterlab_widgets
```

I tried enabling just one and all break CM.

**Comment by gnestor** [comment]
I'm not sure if this is related, but I noticed this error a couple days and it only occurs with specific notebooks (if I copy the source from the notebook and paste it into a new notebook, no problems):

```
Uncaught (in promise) TypeError: CodeMirror.multiplexingMode is not a function
    at http://localhost:8888/lab/extensions.bundle.js:59802:24
    at getMode (http://localhost:8888/labextension/jupyterlab_json/jupyterlab_json.bundle.js:16242:18)
    at loadMode (http://localhost:8888/labextension/jupyterlab_json/jupyterlab_json.bundle.js:19241:18)
    at http://localhost:8888/labextension/jupyterlab_json/jupyterlab_json.bundle.js:21979:6
    at CodeMirror.optionHandlers.(anonymous function) (http://localhost:8888/labextension/jupyterlab_json/jupyterlab_json.bundle.js:21966:64)
    at http://localhost:8888/labextension/jupyterlab_json/jupyterlab_json.bundle.js:18635:21
    at CodeMirror.setOption (http://localhost:8888/labextension/jupyterlab_json/jupyterlab_json.bundle.js:22524:51)
    at http://localhost:8888/lab/extensions.bundle.js:59389:17
```

I can share a _corrupt_ notebook if it makes sense.

**Comment by jasongrout** [comment]
Can you paste what lines of code it's referring to? (i.e., `http://localhost:8888/lab/extensions.bundle.js:59802:24`)

**Comment by gnestor** [comment]
This is resolved now... I believe as of 0.11.0.

**Comment by gnestor** [comment]
I'm seeing this again after upgrading to 0.12.1. This time I'm not seeing the `TypeError: CodeMirror.multiplexingMode is not a function` or any error in the console. Like before, disabling all labextensions (even jupyterlab_widgets) fixes it.

**Comment by gnestor** [comment]
Alas, it's working again! I'm not sure what fixed it, but I did `git pull` a couple dependencies (ipython, ipywidgets). I will close and re-open if it comes back up.

**Comment by AbdealiJK** [comment]
I had the same issue and found that this happens because the extension was built using codemirror 5.23.0 while my jupyterlab was built using 5.22.0

As jupyterlab's package.json has `"codemirror": "^5.20.2",` this is not being caught. It seems this should be changed to `^5.23.0` because codemirror has a breaking change in this version (hence causing this incompatibility)

Could someone reopen this issue ?

**Comment by blink1073** [comment]
Version compatibility checking and enforcement is being tracked in https://github.com/jupyterlab/jupyterlab/issues/1011.    Until we have that in place, any library that JupyterLab is using can cause this problem.   Do you mind opening a new issue with a prompt to upgrade our version of CodeMirror?

**Comment by gnestor** [comment]
Can an extension get an instance of (or interface to) CodeMirror from the jupyterlab module?

**Comment by blink1073** [comment]
Yes, actually, we can export it as a plugin.  Nice idea!

**Comment by AbdealiJK** [comment]
@blink1073 I wasn't using any feature of codemirror actually. This happened for me when I has included `NotebookActions` so I can use the `[run()](https://github.com/jupyterlab/jupyterlab/blob/master/src/notebook/actions.ts#L389)` function to run the cell from my plugin.

When building this with `buildExtension` it automatically included codeMirror in my plugin's bundle and it so happened that this code mirror was 3.23.0 (Because I had done a npm update)

So, I was not using codeMirror, but when I used NotebookActions.run(), buildExtension added it in my bundle.
