### PR TITLE
Upgrade to typescript 3.5.1

### PR DESCRIPTION
**Pull request by jasongrout**
## Code changes

Upgrade to Typescript 3.5.1

## Backwards-incompatible changes

None, other than our dependencies change.

### CODE REVIEW

**Comment by blink1073** [comment]
```
$ tsc -b
../fileeditor-extension/src/index.ts(237,7): error TS2322: Type 'string | number | boolean | number[]' is not assignable to type 'never'.
  Type 'string' is not assignable to type 'never'.
../notebook-extension/src/index.ts(602,7): error TS2322: Type 'string | number | boolean | number[]' is not assignable to type 'never'.
  Type 'string' is not assignable to type 'never'.
../notebook-extension/src/index.ts(612,7): error TS2322: Type 'string | number | boolean | number[]' is not assignable to type 'never'.
  Type 'string' is not assignable to type 'never'.
../notebook-extension/src/index.ts(622,7): error TS2322: Type 'string | number | boolean | number[]' is not assignable to type 'never'.
  Type 'string' is not assignable to type 'never'.
../terminal-extension/src/index.ts(120,7): error TS2322: Type 'JSONPrimitive' is not assignable to type 'never'.
  Type 'string' is not assignable to type 'never'.
```

**Comment by blink1073** [comment]
Uh oh, the Windows build succeeded but actually had the same error as above...

**Comment by jasongrout** [comment]
We are running into problems where we have the following pattern:

```typescript
interface IMy {
  a: number;
  b: string;
  c: boolean;
}

let x: IMy = {
  a: 5,
  b: 'hello',
  c: true
};

Object.keys(x).forEach((k: keyof IMy) => {
  x[k] = 'a';
});
```
That assignment `x[k] = 'a'` works fine in TS 3.4, but TS 3.5 is smarter about the `keyof` union, and realizes that nothing could ever satisfy the type conditions for `'a' | 'b' | 'c'` (which is the keyof type), so `x[keyof x]` is type `never`, so assigning something to it never works.

**Comment by jasongrout** [comment]
Looks like the test failure is something to be fixed in ts-loader: https://github.com/TypeStrong/ts-loader/issues/939, https://github.com/TypeStrong/ts-loader/pull/942

**Comment by blink1073** [comment]
I'd say wait for the patch release of ts-loader since it looks to be imminent.

**Comment by jasongrout** [comment]
> I'd say wait for the patch release of ts-loader since it looks to be imminent.

Yep, I was on the fence about changing this vs waiting for a ts-loader release. At least we'll see if there are any other issues.

**Comment by jasongrout** [comment]
Looks like the updated ts-loader made all of our tests happy now!

File: packages/terminal-extension/src/index.ts [hunk 1]
```diff
@@ -108,17 +108,14 @@ function activate(
...
   /**
-   * Update the option values.
+   * Update the cached option values.
    */
   function updateOptions(settings: ISettingRegistry.ISettings): void {
-    options = settings.composite as Partial<ITerminal.IOptions>;
-    Object.keys(options).forEach((key: keyof ITerminal.IOptions) => {
-      ITerminal.defaultOptions[key] = options[key];
-    });
+    options = settings.composite;
```
Comment (vidartf) [inline packages/terminal-extension/src/index.ts]: Should the `defaultOptions` be made read only (if they are not already)?

Comment (jasongrout) [reply packages/terminal-extension/src/index.ts]: What do you think? I would normally think yes, but they were being written to before.

Comment (vidartf) [reply packages/terminal-extension/src/index.ts]: I don't know what the reasoning was for writing to them in the first place, but I saw you marking this as a typing error, so I was wondering if this should be cleaned up too.

Comment (jasongrout) [reply packages/terminal-extension/src/index.ts]: Ah, the typing error had to do with the way the options were set (the `forEach((key: keyof X))` pattern doesn't work so well anymore), not about writing to the default options.

Comment (jasongrout) [reply packages/terminal-extension/src/index.ts]: If they were really meant to be readonly, we'd probably take them out of the interface file, right?

I wasn't trying to make a decision here about how *all* people use those default options, just how *we* were using them. To prevent scope creep here, and avoid making many design decisions tangential to upgrading to ts 3.5, can we open a separate issue about this (unless there is a clear preference one way or the other)?

(I'm a bit sensitive to scope creep after #6412 ballooned far larger than I anticipated :).

Comment (vidartf) [reply packages/terminal-extension/src/index.ts]: > Ah, the typing error had to do with the way the options were set (the forEach((key: keyof X)) pattern doesn't work so well anymore), not about writing to the default options.

I was wondering whether it was a little naive to take the commit message at face value 😉 I was basically curious if this fix was necessary due to the TS upgrade, or an unrelated fix while you were in the neighborhood 😄

Comment (jasongrout) [reply packages/terminal-extension/src/index.ts]: So...conversation resolved (at least as far as this PR is concerned)?

**Comment by jasongrout** [comment]
Thanks @vidartf and @blink1073 for the reviews.
