### ISSUE TITLE
JupyterLab 3 does not work with `jupyterlab_server=2.10.0`

### ISSUE THREAD

**Issue by trungleduc** [jupyterlab/jupyterlab#11733]
## Description

I got the following errors while starting JupyterLab 3.1.18 with `jupyterlab_server` 2.10.0 installed

```bash
Traceback (most recent call last):
  File "/home/..../miniconda3/envs/test/bin/jupyter-lab", line 6, in <module>
    from jupyterlab.labapp import main
  File "/home/..../miniconda3/envs/test/lib/python3.9/site-packages/jupyterlab/__init__.py", line 7, in <module>
    from .labapp import LabApp
  File "/home/..../miniconda3/envs/test/lib/python3.9/site-packages/jupyterlab/labapp.py", line 18, in <module>
    from jupyterlab_server import WORKSPACE_EXTENSION, LabServerApp, slugify
ImportError: cannot import name 'WORKSPACE_EXTENSION' from 'jupyterlab_server' (/home/..../miniconda3/envs/test/lib/python3.9/site-packages/jupyterlab_server/__init__.py)
```

## Reproduce

Install `jupyterlab-server==2.10.0`  then start JupyterLab
