### ISSUE TITLE
settingregistry.ts doesn't compile with tsc 4.0.5 : validate isn't tested

### ISSUE THREAD

**Issue by SnarkBoojum** [jupyterlab/jupyterlab#9308]
I'm trying to package jupyterlab for the Debian distribution ; it involves also packaging jupyterlab deps until we have what is needed.

And I fell on an error which isn't due to missing packages:
```
src/settingregistry.ts:221:11 - error TS2722: Cannot invoke an object which is possibly 'undefined'.

221     if (!(validate(schema) as boolean)) {
              ~~~~~~~~

src/settingregistry.ts:222:14 - error TS2532: Object is possibly 'undefined'.

222       return validate.errors as ISchemaValidator.IError[];
                 ~~~~~~~~


Found 2 errors.
```

looking at the code, validate has been obtained at line 218 as validator.getSchema('jupyterlab-plugin-schema') ; but if that isn't found, it is indeed undefined and the following lines are faulty.

In line 137, the result of getSchema does get checked before proceeding, so I think it's legit.

**Comment by jasongrout** [comment]
It looks like in current master, we have `validate!`, which asserts that the value is defined (not sure if it is justified yet, just pointing out that that code is not current master):

https://github.com/jupyterlab/jupyterlab/blob/6dceaf365e02205deb4c307fb9460781d6385c24/packages/settingregistry/src/settingregistry.ts#L221

What version are you dealing with?

**Comment by jasongrout** [comment]
Looks like that assertion was added a few months ago, with a FIXME note that subsequently was removed:

https://github.com/jupyterlab/jupyterlab/commit/e62ed3af9d59a9b967c54773680bf899dba6f259#diff-f408a814d303eff9522745c3a24782e0856d38cf38c6b93872260da45cd90df7R221-R222

**Comment by SnarkBoojum** [comment]
Well, I'm looking at the last released version, 2.2.9.
